<?php

use Illuminate\Database\Seeder;

use App\Manga;
use App\Type;
use App\Seller;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $types = [
            "action","adventure","cars","comedy","ecchi","fantasy","hentai","seinen","space","school","magic","drama","game",
            "shoujo","mecha","harem","sports"
        ];

        foreach($types as $type){
            Type::create(["name" => $type]);
        }

        $sellers = [
            [
                "name" => "FNAC",
                "website" => "https://www.fnac.com/",
                "phone" => "0 825 02 00 20",
            ],
            [
                "name" => "Virgin",
                "website" => "https://www.virginradio.fr/",
                "phone" => "01 47 20 00 01",
            ],
            [
                "name" => "Cultura",
                "website" => "https://www.cultura.com/",
                "phone" => "01 41 45 66 50",
            ],
            [
                "name" => "Amazon",
                "website" => "https://www.Amazon.com/",
                "phone" => "01 54 78 54 28",
            ],
            [
                "name" => "Manga-Shop",
                "website" => "https://www.manga-shop.com/",
                "phone" => "01 21 22 88 75",
            ],
            [
                "name" => "Manga-Passion",
                "website" => "https://www.manga-passion.com/",
                "phone" => "01 57 45 68 56",
            ],
            [
                "name" => "Rue du commerce",
                "website" => "https://www.rueducommerce.com/",
                "phone" => "01 47 85 65 38",
            ],
        ];

        foreach($sellers as $seller){
            Seller::create($seller);
        }

        $mangas = [
            [
                "english_name" => "Bleach",
                "japanese_name" => "ブリーチ",
                "synopsis" => "histoire de Bleach se déroule dans une version alternative de notre monde où des shinigami, les dieux de la mort, protègent l'espèce humaine et les âmes des morts des hollows, forme bestiale des âmes perdues. Cette lutte incessante, invisible aux yeux d'une très large majorité d'humains, se fait notamment à l'aide de Zanpakutō, des sabres spirituels liés à leurs maîtres qui peuvent se transformer.",
                "last_publication" => "2001/08/20",
                "next_publication" => null,
                "volumes" => 74,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/anime/00/42/mini/bleach_24.jpg?11524648266",
                "status" => "Published",
            ],
            [
                "english_name" => "Naruto",
                "japanese_name" => "ナルト",
                "synopsis" => "L'histoire de Naruto se déroule dans un monde rétro-futuriste où, bien que de nombreuses technologies modernes aient vu le jour, les ninjas et, dans une moindre mesure, les samouraïs sont restés de véritables puissances militaires. Chaque pays a un village, qui représente la force militaire du pays, dirigé par un Kage. Les villages, à travers leurs ninjas, se livrent des guerres les uns aux autres, à petite ou grande échelle, que ce soit pour obtenir des caractéristiques avantageuses propres aux villages ennemis, ou pour soumettre un autre village et gagner en puissance",
                "last_publication" => "1999/10/04",
                "next_publication" => null,
                "volumes" => 72,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/82/mini/2928.jpg?11504538930",
                "status" => "Published",
            ],
            [
                "english_name" => "Berserk",
                "japanese_name" => "ベルセルク",
                "synopsis" => "Guts, a former mercenary now known as the \"Black Swordsman,\" is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings. Setting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.",
                "last_publication" => "1989/08/25",
                "next_publication" => "2018/07/13",
                "volumes" => 10,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => "https://www.nautiljon.com/images/anime/00/83/berserk_338.jpg",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Blue Corner",
                "japanese_name" => "ナルト",
                "synopsis" => "Reggae est un boxeur mystérieux et mutique qui a débuté sa carrière un jour d'avril 1975 en poids légers et qui, depuis, traîne sa carcasse sur les rings de seconde zone. Pour son 33e match, il perd une nouvelle fois par K.-O., mais ce soir-là, le hasard a placé dans la salle Mister Dangelo, ancien champion du monde en poids mi-lourds, et aujourd'hui organisateur de rencontres. Ce dernier voit alors en Reggae un boxeur hors normes, doté d'un coup de poing exceptionnel. Il décide donc d'acheter le contrat de Reggae à son club actuel pour pouvoir le placer sur des rings plus prestigieux, avec des primes bien plus importantes...",
                "last_publication" => "2017/05/30",
                "next_publication" => "2018/05/30",
                "volumes" => 1,
                "authors" => "Caribu Marley",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/16/mini/28161.jpg?11525851366",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Dark flowers",
                "japanese_name" => "ナルト",
                "synopsis" => "Takao est sur le point de retrouver Sawa, car il est de retour dans son ancien village, son grand père ayant de gros problèmes de santé. Leurs retrouvailles se feront-elles sans encombres ?",
                "last_publication" => "2018/05/31",
                "next_publication" => "2017/05/11",
                "volumes" => 10,
                "country" => "Japan",
                "authors" => "Oshimi Shuzo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/38/mini/23383.jpg?11524672793",
                "status" => "publishing",
            ],
            [
                "english_name" => "Immortal Hounds",
                "japanese_name" => "ナルト",
                "synopsis" => "Le lieutenant Kenzaki a compris que les voies officielles ne lui permettraient pas d'en savoir plus au sujet du SDR. Pragmatique, le policier décide de traiter directement avec les agents de la contamination, à savoir Maman et ses exfiltreuses ! Les deux parties parviennent à un accord : si l'officier aide à libérer Rin, il pourra l'interroger.",
                "last_publication" => "2018/02/21",
                "next_publication" => "2018/05/31",
                "volumes" => 6,
                "country" => "Japan",
                "authors" => "Yasohachi Ryo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/20/mini/27102.jpg?11524672826",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Ad Astra",
                "japanese_name" => "ナルト",
                "synopsis" => "Hasdrubal Giscon a convaincu Syphax, le roi de Numidie occidentale, de se rallier à lui, en échange de la main de sa fille, la belle Sophonisbe. À la nouvelle de cette trahison, le prince Massinissa se joint à Scipion, afin de récupérer sa promise… Hélas, si ces renforts sont bienvenus, ils ne suffisent pas à changer la donne.",
                "last_publication" => "2017/11/17",
                "next_publication" => "2018/05/31",
                "volumes" => 12,
                "country" => "Japan",
                "authors" => "Kagano Mihachi",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/57/mini/27675.jpg?11524672783",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Parallel Destiny",
                "japanese_name" => "ナルト",
                "synopsis" => " Durant son premier rendez-vous avec Chihiro, Yukichi se met à pleurer lorsqu'il se remémore ses sentiments envers Hinata. À la vue de ces larmes, Chihiro décide de lui rendre le miroir à l'origine de leur rencontre et de la naissance de leurs sentiments. Leur histoire d'amour née d'un malentendu va-t-elle se terminer ainsi ?",
                "last_publication" => "2018/02/24",
                "next_publication" => "2018/05/31",
                "volumes" => 3,
                "country" => "Japan",
                "authors" => "Imai Daisuke",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/68/mini/27886.jpg?11526296686",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Dimension W",
                "japanese_name" => "ナルト",
                "synopsis" => "Chargés par Clea Skyheart de découvrir le véritable but des recherches du Dr Yurizaki avant le Syndicat, Kyoma et son équipe décident d'infiltrer la fameuse organisation, qui semble avoir une longueur d'avance.",
                "last_publication" => "2017/10/25",
                "next_publication" => null,
                "volumes" => 14,
                "country" => "Japan",
                "authors" => "Iwahara Yuji",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/48/mini/27984.jpg?11524672809",
                "status" => "Published",
            ],
            [
                "english_name" => "Petals of Reincarnation",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2018/04/10",
                "next_publication" => null,
                "volumes" => 7,
                "country" => "Japan",
                "authors" => "Konishi Mikihisa",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/77/mini/28277.jpg?11527145664",
                "status" => "Published",
            ],
            [
                "english_name" => "Green Mechanic",
                "japanese_name" => "ナルト",
                "synopsis" => "Emmenés contre leur gré dans le secteur interdit, Misha et ses compagnons font la connaissance de Noah, qui, tout comme la jeune fille, a le pouvoir de calmer les Ersatz. Seulement, l'homme refuse de coopérer avec eux pour mettre la main sur Petite Sœur, qui terrorise tout le quartier…",
                "last_publication" => "2018/05/31",
                "next_publication" => "2018/07/25",
                "volumes" => 2,
                "country" => "Japan",
                "authors" => "Iwahara Yuji",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/67/mini/28876.jpg?11524672774",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Strobe Edge",
                "japanese_name" => "ナルト",
                "synopsis" => "Ninako se dit que Ren se comporte avec elle comme avant parce qu'il la considère seulement comme une amie. Mais l'attitude de Ren sème le trouble en elle. Ninako décide d'essayer de tout faire pour devenir sa petite amie, car le pire serait qu'elle le voie tomber amoureux d'une autre. C'est là que Mao, l'ex-petite amie d'Ando au collège, intègre le lycée. C'est à cause d'elle que Ren et Ando ne sont plus aussi bons amis qu'avant. En écoutant l'aveu de Mao, Ninako fait un choix...",
                "last_publication" => "2012/07/06",
                "next_publication" => null,
                "volumes" => 10,
                "country" => "Japan",
                "authors" => "Sakisaka Io",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/77/mini/6677.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Amatsuki",
                "japanese_name" => "ナルト",
                "synopsis" => "Suite à sa rencontre avec l'énigmatique Bonten, Tokidoki s'éveille dans le sanctuaire Sakagami, siège des chasseurs de yôkai. Ses amis et lui sont amicalement accueillis par Shinshu, la jeune soeur de la mystérieuse princesse, mais les défenseurs du sanctuaire, plus méfiants, s'en prennent à eux. Confrontés à leurs démons, les trois voyageurs ne doivent leur salut qu'à l'intervention de la maîtresse des lieux... Des journalistes poursuivent leurs recherches sur le fantomatique Midori Sensai.",
                "last_publication" => "2015/06/16",
                "next_publication" => "2018/11/25",
                "volumes" => 24,
                "country" => "Japan",
                "authors" => "Takayama Shinobu",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/84/mini/4148.jpg?10",
                "status" => "publishing",
            ],
            [
                "english_name" => "Kure-nai",
                "japanese_name" => "ナルト",
                "synopsis" => "Shinkurô, médiateur professionnel, partage à présent son petit appartement avec la jeune Murasaki Kuhôin, dont il a accepté la garde. Tout semble aller pour le mieux, quand soudain Ryûji, le frère aîné de Murasaki, surgit pour la kidnapper. Découvrant le destin funeste qui attend la fillette, Shinkurô se lance alors seul à son secours, et au devant d'un affrontement violent.",
                "last_publication" => "2011/02/17",
                "next_publication" => null,
                "volumes" => 10,
                "country" => "Japan",
                "authors" => "Kentaro Katayama",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/31/mini/4213.jpg?11311458087",
                "status" => "Published",
            ],
            [
                "english_name" => "Black Butler",
                "japanese_name" => "ナルト",
                "synopsis" => "Le manoir est attaqué ! Pour le protégé, ainsi qu'Elizabeth, toujours présente, Finny, May Linn et Bard révèlent leur vraie nature, et leur vrai potentiel ! Le manoir est sauvé... au prix de quelques dégâts.",
                "last_publication" => "2018/01/15",
                "next_publication" => null,
                "volumes" => 14,
                "country" => "Japan",
                "authors" => "Toboso Yana",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/77/mini/1677.jpg?11337007296",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Pink Diary",
                "japanese_name" => "ナルト",
                "synopsis" => "Depuis qu'elle a rencontré Sei, Kiyoko retrouve goût au bonheur pour la première fois depuis quatre ans. Sa rancoeur vis-à-vis de Tommy, son ancien grand amour, s'est même estompée. Sa vie serait idyllique si Kenji, son frère jumeau, n'était pas au plus mal. Après avoir perdu l'amitié de Tommy, Kenji se fait renvoyer du lycée. La petite Sachiko n'est guère plus heureuse. Kiyoko prend les choses en main.",
                "last_publication" => "2017/10/25",
                "next_publication" => null,
                "volumes" => 14,
                "country" => "France",
                "authors" => "Jenny",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/17/mini/1471.jpg?11371735406",
                "status" => "Published",
            ],
            [
                "english_name" => "Trill On Eden",
                "japanese_name" => "ナルト",
                "synopsis" => "Réconciliée avec sa mère qui a enfin accepté que sa fille fasse du chant, Ritsu n’est pourtant pas au bout de ses peines. En effet, l’ancien amour d’Eiri, Kyôko Ogura, réapparaît et jette le trouble dans les sentiments de Ritsu. Malgré les promesses d’Eiri, qui lui assure qu’ils ne sont plus du tout proches, la jeune fille fera tout pour tirer la situation au clair, et s’attirer une montagne d’ennuis...",
                "last_publication" => "2010/08/12",
                "next_publication" => null,
                "volumes" => 8,
                "country" => "Japan",
                "authors" => "Fujita Maki",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/78/mini/5087.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "RH+",
                "japanese_name" => "ナルト",
                "synopsis" => " Kiyoi doit s'absenter pour la journée afin de venir à la rencontre de Michitaka, le petit-fils d'une personne qui a beaucoup compté pour lui. A cette occasion Michitaka se souvient alors de sa première rencontre avec Kiyoi.",
                "last_publication" => "2011/06/22",
                "next_publication" => null,
                "volumes" => 4,
                "country" => "Japan",
                "authors" => "Suwa Ayako",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/09/mini/4790.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "The Legend of Zelda",
                "japanese_name" => "ナルト",
                "synopsis" => "Tetra et sa bande de pirates sillonnent les océans à la recherche de nouvelles terres jusqu'à ce qu'ils découvrent une mer recouverte d'un épais brouillard où mouille un navire abandonné. En voulant l’explorer seule, Tetra se fait enlever par d'étranges puissances maléfiques.",
                "last_publication" => "2014/03/16",
                "next_publication" => null,
                "volumes" => 6,
                "country" => "Japan",
                "authors" => "Himekawa Akira",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/52/mini/6625.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Goyô",
                "japanese_name" => "ナルト",
                "synopsis" => "Masanosuke donne ses derniers conseils de frère aîné à Fuminosuke. Pendant ce temps, une rumeur concernant les Goyô se répand à Edo. Qui a dénoncé les Goyô ? La bande est en proie au doute.",
                "last_publication" => "2017/09/23",
                "next_publication" => null,
                "volumes" => 8,
                "country" => "Japan",
                "authors" => "Ono Natsume",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/21/mini/4712.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Ranma 1/2",
                "japanese_name" => "ナルト",
                "synopsis" => "Le principal de l'école d'Akané revient d'un long voyage à Hawaï. Attention, cet homme n'est pas un principal ordinaire : il adore faire ce que les élèves détestent.",
                "last_publication" => "1997/06/15",
                "next_publication" => null,
                "volumes" => 38,
                "country" => "Japan",
                "authors" => "Takahashi Rumiko",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/61/mini/7916.jpg?11361384238",
                "status" => "Published",
            ],
            [
                "english_name" => "Angel Sanctuary",
                "japanese_name" => "ナルト",
                "synopsis" => "Alors que Rochel est à présent libre et désire assouvir sa vengeance sur l'âme réincarnée de sa soeur jumelle, Setsuna se retrouve confronté à d'autres problèmes. Des démons l'attaquent fréquemment et il apprend en plus que sa chère soeur Sara partira sous peu, pour peut-être ne plus jamais le revoir...",
                "last_publication" => "2003/10/11",
                "next_publication" => null,
                "volumes" => 20,
                "country" => "Japan",
                "authors" => "Yuki Kaori",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/33/mini/33.jpg?11336405114",
                "status" => "Published",
            ],
            [
                "english_name" => "Akari",
                "japanese_name" => "ナルト",
                "synopsis" => "Akari Hamada aurait pu vivre une adolescence normale sans la banqueroute de la société de son père. Ruiné et endetté, ce dernier envoie sa fille “en paiement” auprès de la société Otomo à qui il doit plusieurs millions.",
                "last_publication" => "2007/10/24",
                "next_publication" => null,
                "volumes" => 9,
                "country" => "Japan",
                "authors" => "Takada Rie",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/59/mini/5295.jpg?11361554661",
                "status" => "Published",
            ],
            [
                "english_name" => "Belong Them",
                "japanese_name" => "ナルト",
                "synopsis" => "Mizuki étant découverte, les responsables de dortoir savent désormais la vérité sur elle et cette dernière va devoir assumer les conséquences de ses actes : à la fin de l'année, elle devra quitter l'établissement... et donc Sano ! Mais avant tout, elle devra éclaircir les choses avec ses amis surtout avec Nakatsu !",
                "last_publication" => "2008/11/19",
                "next_publication" => null,
                "volumes" => 24,
                "country" => "Japan",
                "authors" => "Nakajo Hisaya",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/79/mini/197.jpg?11504678975",
                "status" => "Published",
            ],
            [
                "english_name" => "Spiral",
                "japanese_name" => "ナルト",
                "synopsis" => "Une jeune fille fait une chute mortelle du sixième étage d'un bâtiment du lycée Tsukiomi. Un témoin, Mizue Nohara, amie de la victime, affirme avoir vu Narumi sur le palier, quelques secondes après la chute de la victime.",
                "last_publication" => "2010/02/01",
                "next_publication" => null,
                "volumes" => 15,
                "country" => "Japan",
                "authors" => "Shirodaira Kyo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/24/mini/4742.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Love Mode",
                "japanese_name" => "ナルト",
                "synopsis" => "Aoe Reiji est âgé de 23ans et décide de partir en vacance à Londres. Dès son premier jour il accumule la malchance : il se fait arnaquer par une femme, la nourriture du restaurant était infecte.",
                "last_publication" => "2011/08/21",
                "next_publication" => null,
                "volumes" => 11,
                "country" => "Japan",
                "authors" => "Shimizu Yuki",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/17/mini/1871.jpg?11360406350",
                "status" => "Published",
            ],
            [
                "english_name" => "Liar Game",
                "japanese_name" => "ナルト",
                "synopsis" => "Deuxième épreuve du Revival Round, Akiyama affronte Kikuchi dans une partie de poker aux règles bien particulières. Mais il aura fort à faire car son adversaire est un ancien boxeur à la vue perçante, ce qui lui permet de distinguer les cartes lors de la distribution !!",
                "last_publication" => "2017/10/25",
                "next_publication" => null,
                "volumes" => 19,
                "country" => "Japan",
                "authors" => "Kaitani Shinobu",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/78/mini/4287.jpg?11352550274",
                "status" => "Published",
            ],
            [
                "english_name" => "Gantz",
                "japanese_name" => "ナルト",
                "synopsis" => "Toujours en prise contre l'énorme Bouddha, Keï et ses compagnons ont bien du mal a lui tenir tête. D'autant que le garçon, forte tête, a décidé de l'affronter en combat singulier. Les choses se corsent de nouveau, quand toute l'équipe constate que certaines statues sont capables de passer outre leur combinaison de protection et de les trancher comme si de rien n'était...",
                "last_publication" => "2004/10/21",
                "next_publication" => null,
                "volumes" => 37,
                "country" => "Japan",
                "authors" => "Oku Hiroya",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/59/mini/4395.jpg?11351279272",
                "status" => "Published",
            ],
            [
                "english_name" => "Seven Days",
                "japanese_name" => "ナルト",
                "synopsis" => "Lundi matin, devant le portail du lycée, Yuzuru Shino, élève de terminale, s'adresse à Tôji Seryô de deux ans son cadet. Ce dernier est réputé pour accepter de sortir avec la fille qui lui demande, en début de semaine, mais qui stoppe toujours la relation le week-end venu.",
                "last_publication" => "2018/05/31",
                "next_publication" => null,
                "volumes" => 2,
                "country" => "Japan",
                "authors" => "Tachibana Venio",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/32/mini/4223.jpg?11311458920",
                "status" => "Published",
            ],
            [
                "english_name" => "I love sushis",
                "japanese_name" => "ナルト",
                "synopsis" => "Comprenant qu’elle a échoué à ses examens, Hanayu est prête à interrompre son stage dans le restaurant de la famille Hyûga, renonçant ainsi à son rêve. Mais Hayato ne l’entend pas de la même oreille. Afin qu’elle puisse devenir maître sushi, il propose à Hanayu... de l’épouser ?! Mais les choses se compliquent encore quand Maezawa, l’assistant de son père, s’invite dans leur histoire...",
                "last_publication" => "2018/01/14",
                "next_publication" => null,
                "volumes" => 8,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/10/mini/7301.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Real V",
                "japanese_name" => "ナルト",
                "synopsis" => "Nomiya est au lycée. Il se distingue des autres par une coupe afro, une carrure impressionnante et un air nonchalant. Sa passion, c'était le basket-ball, mais il a tout abandonné après l'accident de moto qui a coûté ses jambes à la jeune Natsumi Yamashita. Torturé par la culpabilité, il va lui rendre visite très régulièrement.",
                "last_publication" => "2017/05/28",
                "next_publication" => "2018/08/28",
                "volumes" => 2,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/14/mini/5941.jpg?10",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Monochrome Animals",
                "japanese_name" => "ナルト",
                "synopsis" => "Kureha, de manière inattendue, est devenue présidente du BDE de Kedako. Mais après son discours d'investiture, ce qui l'attend est la cérémonie de couronnement, consistant à recevoir...",
                "last_publication" => "2018/05/31",
                "next_publication" => null,
                "volumes" => 12,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/90/mini/5909.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Not ready?!",
                "japanese_name" => "ナルト",
                "synopsis" => "Murakami Hiroshi est un mangaka spécialisé dans le yaoi qui clame haut et fort son hétérosexualité. Il a d'ailleurs une petite amie mais il couche régulièrement avec d'autres hommes, allant même jusqu'à séduire son assistant.",
                "last_publication" => "2018/04/10",
                "next_publication" => null,
                "volumes" => 1,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/79/mini/3697.jpg?11363602709",
                "status" => "Published",
            ],
            [
                "english_name" => "Stray Little Devil",
                "japanese_name" => "ナルト",
                "synopsis" => "Des examens chez les démons ?! Eh oui ! Même loin de chez elle, Pam n'y coupe pas. Elle doit à tout prix réussir sa première année pour devenir un vrai démon et pouvoir un jour rentrer chez elle...",
                "last_publication" => "2007/06/28",
                "next_publication" => null,
                "volumes" => 5,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/65/mini/3456.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Sailor Moon",
                "japanese_name" => "ナルト",
                "synopsis" => "Mamoru se fait enlever par le royaume des ténèbres, dans le but de le retrouver, Bunny et ses amies vont aller sur la lune pour retracer leur passé ! De retour sur Terre, Bunny aperçoit un jeune homme ressemblant à Mamoru, à sa grande surprise cet homme n'est autre que Tuxedo...",
                "last_publication" => "1998/03/23",
                "next_publication" => null,
                "volumes" => 18,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/33/mini/633.jpg?11357838308",
                "status" => "Published",
            ],
            [
                "english_name" => "Witch Hunter",
                "japanese_name" => "ナルト",
                "synopsis" => "Alors que Tasha, très déprimé par ses échecs successifs et son combat contre Ryu Hwang, doit s'habituer à la nouvelle forme de son supporter Halloween.",
                "last_publication" => "2008/05/31",
                "next_publication" => null,
                "volumes" => 19,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/63/mini/436.jpg?11504533665",
                "status" => "Published",
            ],
            [
                "english_name" => "Yu-Gi-Oh !",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2008/05/15",
                "next_publication" => null,
                "volumes" => 20,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/49/mini/5494.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Neuro",
                "japanese_name" => "ナルト",
                "synopsis" => "Quel est le secret caché derrière elle, l'oeuvre inachevée du sculpteur Eshiya ? ",
                "last_publication" => "2009/05/31",
                "next_publication" => null,
                "volumes" => 23,
                "country" => "Japan",
                "authors" => "Masashi Kishimoto",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/02/mini/1920.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Midnight Wolf",
                "japanese_name" => "ナルト",
                "synopsis" => "Après ce tome 6 pleins de rebondissements, nous retrouvons nos héros en Allemagne, suite à une surprenante nouvelle qui leur permet de voyager dans le pays natal de Yato. La belle Hisako, va en savoir plus sur le passé de son bien aimé. Mais sur place, Yato va retrouver bien plus que ses racines...",
                "last_publication" => "2012/11/21",
                "next_publication" => null,
                "volumes" => 10,
                "country" => "Japan",
                "authors" => "Tachibana Venio",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/50/mini/7805.jpg?10",
                "status" => "Published",
            ],
            [
                "english_name" => "Grendel",
                "japanese_name" => "ナルト",
                "synopsis" => "Camélia, une chevalière d'exception, a été condamnée à mort pour trahison.",
                "last_publication" => "2016/05/31",
                "next_publication" => "2018/07/27",
                "volumes" => 7,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/68/mini/28886.jpg?11526313374",
                "status" => "publishing",
            ],
            [
                "english_name" => "Between dog and wolf",
                "japanese_name" => "ナルト",
                "synopsis" => "Publié en exclusivité mondiale, ce recueil de 12 nouvelles nous entraine dans une Chine rurale à l'ambiance crépusculaire et mystifiante !",
                "last_publication" => "2017/06/02",
                "next_publication" => "2018/06/03",
                "volumes" => 12,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/11/mini/29611.jpg?11527236448",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Yamada Kun & the 7 Witches",
                "japanese_name" => "ナルト",
                "synopsis" => "Les échecs s'enchaînent bien que le pouvoir de Yuri soit entre les mains de Yamada. Kaori décide néanmoins de lui révéler des informations sur Yuri.",
                "last_publication" => "2015/05/01",
                "next_publication" => "2018/07/01",
                "volumes" => 17,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/75/mini/21857.jpg?11524074869",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Waiting For Spring",
                "japanese_name" => "ナルト",
                "synopsis" => "Mitsuki a revu Aya et a découvert que son amie d'enfance est en réalité un homme ! La jeune fille se sent également mal vis à vis de Towa, qui semble s'éloigner depuis cette retrouvaille.",
                "last_publication" => "2014/05/20",
                "next_publication" => "2018/06/08",
                "volumes" => 1,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/74/mini/23347.jpg?11522534072",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Koi Furu Colorful",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2018/01/30",
                "next_publication" => "2018/05/31",
                "volumes" => 4,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => null,
                "status" => "Publishing",
            ],
            [
                "english_name" => "Seven Deadly Sins",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2014/07/20",
                "next_publication" => "2019/05/24",
                "volumes" => 26,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/49/mini/27094.jpg?11522534012",
                "status" => "Publishing",
            ],
            [
                "english_name" => "La Courtisane d'Edo",
                "japanese_name" => "ナルト",
                "synopsis" => "Akane fait l'objet de brimades, mais elle peut compter sur l'aide de Riichi. Akane voit également ses sentiments pour Oumiya évoluer.",
                "last_publication" => "2012/04/14",
                "next_publication" => "2019/05/31",
                "volumes" => 1,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/12/mini/27321.jpg?11522524988",
                "status" => "Publishing",
            ],
            [
                "english_name" => "To the Abandoned Sacred Beasts",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2017/05/31",
                "next_publication" => "2018/07/04",
                "volumes" => 7,
                "country" => "Japan",
                "authors" => "Tachibana Venio",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/87/mini/27378.jpg?11522534053",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Dead Tube",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2017/04/07",
                "next_publication" => "2018/11/13",
                "volumes" => 7,
                "country" => "Japan",
                "authors" => "Mirua Kentarou",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/80/mini/27508.jpg?11524074878",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Re:Load",
                "japanese_name" => "ナルト",
                "synopsis" => "N/C",
                "last_publication" => "2017/01/01",
                "next_publication" => "2021/02/21",
                "volumes" => 2,
                "country" => "Japan",
                "authors" => "Tachibana Venio",
                "cover_picture" => "https://www.nautiljon.com/images/manga_volumes/00/87/mini/27578.jpg?11520870597",
                "status" => "Publishing",
            ],
            [
                "english_name" => "Redrum 327",
                "japanese_name" => "ナルト",
                "synopsis" => "Au fur et à mesure que les fils de notre destin se dénouent, nous entendons résonner au loin la symphonie de la mort !",
                "last_publication" => "2018/01/05",
                "next_publication" => "2018/05/28",
                "volumes" => 14,
                "country" => "Japan",
                "authors" => "Tite Kubo",
                "cover_picture" => "https://www.nautiljon.com/images/manga/00/20/mini/redrum_327_8802.jpg?11527509410",
                "status" => "Publishing",
            ],







        ];

        foreach($mangas as $manga){

            $manga = Manga::create($manga);

        }



/*        foreach($mangas as $manga){

            $manga = Manga::create($manga);

            $manga->types()->attach([1,2,4]);
            $manga->sellers()->attach([1,3]);
            $manga->resellers()->attach([1,2]);
        }*/





    }
}

